stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy
  - deployment: VMDeploy
    displayName: green
    pool:
      vmImage: 'Windows'
    environment:
      name: BlueGreen
      resourceType: VirtualMachine
      tags: green
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Downloading the source code from Azure blob storage container to the Azure VM..."
- stage: Deploy_TM
  displayName: TM update weight stage
  jobs:
  - job: Deploy
    displayName: Deploy
  - deployment: VMDeploy
    displayName: green
    pool:
      vmImage: 'Windows'
    environment:
      name: BlueGreen
      resourceType: VirtualMachine
      tags: green
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              /bin/bash /DevOps-Terraform/blue_green_weightage.sh